FROM registry.redhat.io/ubi9/ubi:latest
RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm --nogpgcheck && \
    dnf -y copr enable mczernek/vale && \
    dnf -y install vale rubygem-asciidoctor && \
    dnf -y copr disable mczernek/vale && \
    dnf -y update && \
    dnf -y clean all && \
    rm -rf /tmp/*.rpm && \
    useradd --shell /bin/bash client
COPY files/vale-styles /home/client/.vale-styles
COPY files/vale-styles/vale.ini.template /home/client/.vale.ini

LABEL "vale.commit.hash"="9c5c2b651e41c83213a3d9e591145dd0c7f75829"
LABEL "vale.commit.date"="Thu May 7 22:18:58 2026 +1000"

USER client

ENTRYPOINT ["/bin/vale"]
