#!/bin/bash

FILE="${1}"
CONTANIER_IMAGE="quay.io/redhattraining/vale"
#CONTANIER_IMAGE="quay.io/angelesphillips/vale" # Existing private image
if [[ -n "${FILE}" ]]
then
  if [[ -f "${FILE}" && -r "${FILE}" ]]
  then
    podman images -n ${CONTANIER_IMAGE} | grep -q ${CONTANIER_IMAGE}
    if [[ $? -eq 0 ]]
    then
      podman run --rm -v $(pwd)/${FILE}:$(pwd)/${FILE}:Z ${CONTANIER_IMAGE} $(pwd)/${FILE}
    else
      echo "Run: podman pull ${CONTANIER_IMAGE}" 1>&2
      exit 3
    fi
  else
    echo "'${FILE}' must be a readable file." 1>&2
    exit 2
  fi
else
  echo "Syntax: vale <PATH-TO-FILE>" 1>&2
  exit 1
fi
