---
- name: Build and push the container
  hosts: workstation
  become: true
  become_user: student
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: >-
        Build container: {{ container_name }}
      containers.podman.podman_image:
        name: "{{ container_name }}"
        path: "{{ build_dir }}"
        build:
          cache: false
          force_rm: true
          rm: true
          format: oci

    - name: Identify vale version for tag
      ansible.builtin.command:
        cmd: >-
          podman run --rm
          localhost/{{ container_name }}
          pre-commit --version
      changed_when: false
      register: query_version

    - name: Set container_version
      vars:
        delimiter: ' '
      ansible.builtin.set_fact:
        container_version: >-
          {{ query_version['stdout'] | split(delimiter) | last }}

    - name: >-
        Add tags to image: {{ container_name }}
      containers.podman.podman_tag:
        image: >-
          localhost/{{ container_name }}
        target_names:
          - "{{ quay_name }}:{{ container_version }}"
          - "{{ quay_name }}:latest"

#    - name: >-
#        Push container image to quay.io: {{ quay_name }}
#      tags: push
#      containers.podman.podman_image:
#        name: "{{ item }}"
#        push: true
#      loop:
#        - "{{ quay_name }}:{{ container_version }}"
#        - "{{ quay_name }}:latest"
