#!/bin/bash

FILE="${1}"
CONTANIER_IMAGE="quay.io/redhattraining/spellr"
#CONTANIER_IMAGE="quay.io/angelesphillips/spellr" # Existing private image
if [[ -n "${FILE}" ]]
then
  if [[ -f "${FILE}" && -r "${FILE}" ]]
  then
    podman images -n ${CONTANIER_IMAGE} | grep -q ${CONTANIER_IMAGE}
    if [[ $? -eq 0 ]]
    then
      unset FILE_TO_CHECK
      export FILE_TO_CHECK="$(cat ${FILE})"
      podman run --rm --env FILE_TO_CHECK ${CONTANIER_IMAGE}
    else
      echo "Run: podman pull ${CONTANIER_IMAGE}" 1>&2
      exit 3
    fi
  else
    echo "'${FILE}' must be a readable file." 1>&2
    exit 2
  fi
else
  echo "Syntax: spellr <PATH-TO-FILE>" 1>&2
  exit 1
fi
